[package]
name = "double_linked_list_test-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
slotmap = "1"
ascii_table = "4"

[profile.release]
lto = "fat"

[features]
MAKE_INLINE = []
TEST_MODE = []

